FreshFarmMarket/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace FreshFarmMarket.Models
{
    public class Login
    {
        [Required, RegularExpression(@"^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$", ErrorMessage = "Invalid Email Address")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{12,}$",
            ErrorMessage = "Password requires minimum 12 characters,\r\nUse combination of lower-case, upper-case, Numbers and special characters")]
        [Compare(nameof(Password), ErrorMessage = "Password and confirmation password does not match")]
        public string ConfirmPassword { get; set; }

        public string? Token { set; get; }
        public bool RememberMe { get; set; } = false;
    }
}

FreshFarmMarket/Pages/UserPage/Login.cshtml.cs
using FreshFarmMarket.ViewModels;
using FreshFarmMarket.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FreshFarmMarket.Library;
using FreshFarmMarket.Models;

namespace FreshFarmMarket.Pages.UserPage
{
    public class LoginModel : PageModel
    {
		private readonly SignInManager<User> _signInManager;

		private readonly UserManager<User> _userManager;

		private readonly IHttpContextAccessor _httpContextAccessor;

		private readonly GoogleCaptcha _captchaservice;

        [BindProperty]
        public Login LModel { get; set; }

        public LoginModel(SignInManager<User> signInManager, UserManager<User> userManager, IHttpContextAccessor httpContextAccessor, GoogleCaptcha captchaservice)
		{
			_signInManager = signInManager;
			_httpContextAccessor = httpContextAccessor;
			_captchaservice = captchaservice;
			_userManager = userManager;
		}


		[HttpGet]
		[AllowAnonymous]
		public void OnGet()
		{

		}

		public async Task<IActionResult> OnPostGoogle()
		{
			return Challenge(_signInManager.ConfigureExternalAuthenticationProperties("Google", "/GoogleLogin"), "Google");
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> OnPostAsync()
		{
			if (ModelState.IsValid)
			{
                Console.WriteLine("Signing in");
                var identityResult = await _signInManager.PasswordSignInAsync(LModel.Email, LModel.Password, LModel.RememberMe, true);
                if (identityResult.Succeeded)
                {
                    Console.WriteLine("Success");


                    _httpContextAccessor.HttpContext.Session.SetString(SessionVariable.UserName, LModel.Email);

                    return RedirectToPage("Index");
                }
                else if (identityResult.IsLockedOut)
                {
                    ModelState.AddModelError("", "The account is locked out");
                    return Page();
                }

                Console.WriteLine("Failed");
                ModelState.AddModelError(nameof(LModel.Email), "Username or Password is incorrect");
                return Page();
			}
			else
			{

                Console.WriteLine("Model is INVALID");
                return Page();
            }

			
		}
	}
}

FreshFarmMarket/Pages/UserPage/Logout.cshtml.cs
using FreshFarmMarket.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshFarmMarket.Pages.UserPage
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;
        private readonly IHttpContextAccessor _contxt;

        public LogoutModel(IHttpContextAccessor httpContextAccessor, SignInManager<User> signInManager)
        {
            _signInManager = signInManager;
            _contxt = httpContextAccessor;
        }
        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                _signInManager.SignOutAsync();
                _contxt.HttpContext.Session.Clear();
            }
            return RedirectToPage("Index");
        }
      
        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("Login");
        }
    }
}

FreshFarmMarket/Pages/UserPage/Register.cshtml.cs
using FreshFarmMarket.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.DataProtection;
using FreshFarmMarket.Models;

namespace FreshFarmMarket.Pages.UserPage
{
    public class RegisterModel : PageModel
    {
        [BindProperty]
        public IFormFile? Upload { get; set; }

        [BindProperty]
        public User RModel { get; set; }

        [BindProperty]
        public Login LModel { get; set; }

        private UserManager<User> userManager { get; }

        private SignInManager<User> signInManager { get; }

        private IWebHostEnvironment _environment;

        private readonly IDataProtector _protector;

        private readonly IHttpContextAccessor _contxt;

        public RegisterModel(IHttpContextAccessor httpContextAccessor, IDataProtectionProvider provider, UserManager<User> userManager, SignInManager<User> signInManager, IWebHostEnvironment environment)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            _environment = environment;
            _contxt = httpContextAccessor;
            _protector = provider.CreateProtector("credit_card_protector");

        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                if (Upload != null)
                {
                    if (Upload.Length > 2 * 1024 * 1024)
                    {
                        ModelState.AddModelError("Upload", "File size cannot exceed 2MB.");
                        return Page();
                    }

                    var uploadsFolder = "uploads";
                    var imageFile = Guid.NewGuid() + Path.GetExtension(Upload.FileName);
                    var imagePath = Path.Combine(_environment.ContentRootPath, "wwwroot", uploadsFolder, imageFile);
                    using var fileStream = new FileStream(imagePath, FileMode.Create);
                    await Upload.CopyToAsync(fileStream);
                    var ImageURL = string.Format("/{0}/{1}", uploadsFolder, imageFile);


                    var protectedCreditCardNumber = _protector.Protect(RModel.CreditCard);
                    Console.WriteLine(protectedCreditCardNumber);


                    var user = new User
                    {
                        UserName = LModel.Email,
                        ImageUrl = ImageURL,
                        FullName = RModel.FullName,
                        Gender = RModel.Gender,
                        Email = LModel.Email,
                        MobilNo = RModel.MobilNo,
                        Address = RModel.Address,
                        CreditCard = protectedCreditCardNumber,
                        AboutMe = RModel.AboutMe
                    };



                    var result = await userManager.CreateAsync(user, LModel.Password);
                    if (result.Succeeded)
                    {
                        return RedirectToPage("Login");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }

                }
            }
            return Page();
        }

    }
}

FreshFarmMarket/Pages/UserPage/Login.cshtml
@page
@using Microsoft.Extensions.Options
@using FreshFarmMarket.ViewModels
@inject IOptions<GoogleCaptchaConfig> GoogleCaptchaConfig
@model FreshFarmMarket.Pages.UserPage.LoginModel
@{
	ViewData["Title"] = "Login";
}

<div class="row justify-content-center align-items-center">

	<div class="col-sm-12 col-md-12 col-lg-4">
		<h1 class="mb-3">@ViewData["Title"]</h1>

		<form method="post">

			<div class="mb-3">
				<label class="form-label" asp-for="LModel.Email">Email</label>
				<input type="Text" asp-for="LModel.Email" class="form-control" />
				<span asp-validaton-for="LModel.Email" class="text-danger"></span>
			</div>

			<div class="mb-3">
				<label class="form-label" asp-for="LModel.Password">Password</label>
				<input type="password" asp-for="LModel.Password" class="form-control" />
				<span asp-validaton-for="LModel.Password" class="text-danger"></span>
			</div>

			<div class="mb-3 form-check">
				<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
				<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
			</div>

			<div class="mb-3">
				<button type="submit" class="btn btn-primary">Login</button>
			</div>
		</form>

		<form method="post" class="d-grid gap-3" asp-page-handler="Google">
			<button type="submit" class="btn btn-primary">Login by Google</button>
		</form>
	</div>
</div>


<script src="https://www.google.com/recaptcha/api.js?render=@GoogleCaptchaConfig.Value.SiteKey"></script>

FreshFarmMarket/Pages/UserPage/Logout.cshtml
@page
@model FreshFarmMarket.Pages.UserPage.LogoutModel
@{
}

<p>Thats all for my DEMO!</p>

FreshFarmMarket/Pages/UserPage/Register.cshtml
@page
@model FreshFarmMarket.Pages.UserPage.RegisterModel
@{
}


<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Register </h1>

			<form method="post" enctype="multipart/form-data" asp-antiforgery="true">
				<div asp-validation-summary="All" class="text-danger"></div>
				<div class="col-md-4">
					<div class="form-outline">
						<label class="form-label" asp-for="Upload">Photo</label>
						<input type="file" accept="image/*" asp-for="Upload" class="form-control" onchange="showImgPreview(this)" />
						<span asp-validation-for="Upload" class="text-danger"></span>
					</div>
					<img id="imgPreview" class="rounded-circle" style="height:300px;width:300px;object-fit:cover" src="/uploads/user.png" />
					<input class="form-control d-none" asp-for="RModel.ImageUrl" />
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.FullName">Full Name</label>
					<input type="Text" asp-for="RModel.FullName" class="form-control" />
					<span asp-validaton-for="RModel.FullName" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.CreditCard">Credit Card No</label>
					<input type="Text" asp-for="RModel.CreditCard" class="form-control" />
					<span asp-validaton-for="RModel.CreditCard" class="text-danger"></span>
				</div>

				<div class="form-outline mb-4">
					<div class="form-outline">
						<label class="form-label" asp-for="RModel.Gender">Gender</label><br />
						<div class="form-check form-check-inline mb-0 me-4">
							<input type="radio" asp-for="RModel.Gender" value="male" /> Male
						</div>
						<div class="form-check form-check-inline mb-0 me-4">
							<input type="radio" asp-for="RModel.Gender" value="female" /> Female
						</div>

						<span asp-validaton-for="RModel.Gender" class="text-danger"></span>
					</div>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.MobilNo">Mobile Number</label>
					<input type="Text" asp-for="RModel.MobilNo" class="form-control" />
					<span asp-validaton-for="RModel.MobileNo" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Address">Delivery Address</label>
					<input type="Text" asp-for="RModel.Address" class="form-control" />
					<span asp-validaton-for="RModel.DevAddress" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="Text" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.ConfirmPassword">Confirm Password</label>
					<input type="Text" asp-for="LModel.ConfirmPassword" class="form-control" />
					<span asp-validaton-for="LModel.ConfirmPassword" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.AboutMe">About Me</label>
					<textarea type="Text" asp-for="RModel.AboutMe" class="form-control"></textarea>
					<span asp-validaton-for="RModel.AboutMe" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Register</button>
				</div>
			</form>
		</div>
	</div>
</div>

<script>
	function showImgPreview(input) {
		if (input.files[0]) {
			var uploadimg = new FileReader();
			uploadimg.onload = function (displayimg) {
				$("#imgPreview").attr('src', displayimg.target.result);
			}
			uploadimg.readAsDataURL(input.files[0]);
		}
	}
</script>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
    }